name: build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    strategy:
      matrix:
        target:
        - x86_64-pc-windows-gnu
        - x86_64-unknown-linux-musl
        - aarch64-unknown-linux-musl
        - aarch64-apple-darwin
    runs-on: ${{ matrix.target == 'aarch64-apple-darwin' && 'macos-latest' || 'ubuntu-latest' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache rust dependencies
      id: cache-dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.target }}

    - name: Cache node_modules
      id: cache-node
      uses: actions/cache@v4
      with:
        path: |
          web/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}-${{ matrix.target }}

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: yarn
        cache-dependency-path: web/yarn.lock

    - name: Setup Rust toolchain
      run: |
        rustup toolchain install stable
        rustup default stable
        rustup target add ${{ matrix.target }}

    - name: Generate TypeScript bindings
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: test
        args: --release --locked --target ${{ matrix.target }}

    - name: Build the Web UI
      run: |
        pushd web
        yarn install --frozen-lockfile
        yarn build
        popd

    - name: Build hoshinova
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --locked --target ${{ matrix.target }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}
        path: |
          target/**/release/hoshinova*
          !target/**/release/hoshinova.d
